############################################################
#        __  ___                      _       ____  ___    #
#       /  |/  /___ _____  ____ _____| |     / /  |/  /    #
#      / /|_/ / __ `/ __ \/ __ `/ __ \ | /| / / /|_/ /     #
#     / /  / / /_/ / / / / /_/ / /_/ / |/ |/ / /  / /      #
#    /_/  /_/\__,_/_/ /_/\__, /\____/|__/|__/_/  /_/       #
#                       /____/                             #
############################################################

source=~/.config/mango/modules/autostart.conf
source=~/.config/mango/modules/keybinding.conf
source=~/.config/mango/modules/animation.conf
source=~/.config/mango/modules/window_effect.conf
source=~/.config/mango/modules/appearance.conf
source=~/.config/mango/modules/layout.conf
source=~/.config/mango/modules/rule.conf
source=~/.config/mango/modules/input.conf
source=~/.config/mango/modules/misc.conf
